language: php

php:
    - 5.4
    - 5.6
    - 7.0
env:
    - GUZZLE=3
    - GUZZLE=5
    - GUZZLE=6

git:
    depth: 3

before_script:
    - composer update

matrix:
    exclude:
        - php: 5.4
          env: GUZZLE=5
        - php: 5.4
          env: GUZZLE=6

script:
    - ./vendor/bin/phpcs --standard=phpcs.xml src
    - if [[ $GUZZLE  = 3 ]]; then composer require guzzlehttp/guzzle:3.*; fi
    - if [[ $GUZZLE  = 5 ]]; then composer require guzzlehttp/guzzle:5.*; fi
    - if [[ $GUZZLE  = 6 ]]; then composer require guzzlehttp/guzzle:6.*; fi
    - ./vendor/bin/phpunit -c . --verbose